# Updates the player .json file from config

name: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install git+https://github.com/microprediction/microprediction.git
            pip install --upgrade statsmodels
            pip install matplotlib
      - name: run config
        run: |
          python config.py
      - name: Show git status
        run: | 
          git status
      - name: Add data files  
        run: |
          git config --local user.name  ${{ github.actor }}
          git config --local user.email "my@email.com"
          git add --all           
      - name: Show git status
        run: | 
          git status
      
      - name: Commit
        run: |  
          git commit -a -m "writing player JSON file"
          
      - name: Show git status
        run: | 
          git status
                    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
